spring:
  application:
    name: @project.name@
    version: @project.version@
logging:
  file:
    name: ${user.home}/dinosaur/logs/dinosaur.log
  logback:
    rollingpolicy:
      max-history: 1024
      max-file-size: 64MB