spring:
  application:
    name: @project.name@
    version: @project.version@
  threads:
    virtual:
      enabled: true
logging:
  file:
    name: ${user.home}/dinosaur/logs/dinosaur.log
  logback:
    rollingpolicy:
      max-history: 128
      max-file-size: 128MB